name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every end of month
    - cron: "* * 28 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.USER_CUSTOM_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
